/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NewsRouteImport } from './routes/news'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsIndexRouteImport } from './routes/terms.index'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as SearchIndexRouteImport } from './routes/search.index'
import { Route as RulesIndexRouteImport } from './routes/rules.index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy.index'
import { Route as MembersIndexRouteImport } from './routes/members.index'
import { Route as LeaderboardsIndexRouteImport } from './routes/leaderboards.index'
import { Route as GamemodesIndexRouteImport } from './routes/gamemodes.index'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as BearprimeIndexRouteImport } from './routes/bearprime.index'
import { Route as BearcoinIndexRouteImport } from './routes/bearcoin.index'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as MembersUsernameRouteImport } from './routes/members.$username'
import { Route as GamemodesModeRouteImport } from './routes/gamemodes.$mode'
import { Route as ForumViewSlugRouteImport } from './routes/forum.view.$slug'
import { Route as ForumTopicSlugRouteImport } from './routes/forum.topic.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIndexRoute = RulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsIndexRoute = LeaderboardsIndexRouteImport.update({
  id: '/leaderboards/',
  path: '/leaderboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamemodesIndexRoute = GamemodesIndexRouteImport.update({
  id: '/gamemodes/',
  path: '/gamemodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const BearprimeIndexRoute = BearprimeIndexRouteImport.update({
  id: '/bearprime/',
  path: '/bearprime/',
  getParentRoute: () => rootRouteImport,
} as any)
const BearcoinIndexRoute = BearcoinIndexRouteImport.update({
  id: '/bearcoin/',
  path: '/bearcoin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersUsernameRoute = MembersUsernameRouteImport.update({
  id: '/members/$username',
  path: '/members/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const GamemodesModeRoute = GamemodesModeRouteImport.update({
  id: '/gamemodes/$mode',
  path: '/gamemodes/$mode',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumViewSlugRoute = ForumViewSlugRouteImport.update({
  id: '/forum/view/$slug',
  path: '/forum/view/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumTopicSlugRoute = ForumTopicSlugRouteImport.update({
  id: '/forum/topic/$slug',
  path: '/forum/topic/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gamemodes/$mode': typeof GamemodesModeRoute
  '/members/$username': typeof MembersUsernameRoute
  '/post/$slug': typeof PostSlugRoute
  '/bearcoin/': typeof BearcoinIndexRoute
  '/bearprime/': typeof BearprimeIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/gamemodes/': typeof GamemodesIndexRoute
  '/leaderboards/': typeof LeaderboardsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/rules/': typeof RulesIndexRoute
  '/search/': typeof SearchIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/store/': typeof StoreIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/forum/topic/$slug': typeof ForumTopicSlugRoute
  '/forum/view/$slug': typeof ForumViewSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gamemodes/$mode': typeof GamemodesModeRoute
  '/members/$username': typeof MembersUsernameRoute
  '/post/$slug': typeof PostSlugRoute
  '/bearcoin': typeof BearcoinIndexRoute
  '/bearprime': typeof BearprimeIndexRoute
  '/forum': typeof ForumIndexRoute
  '/gamemodes': typeof GamemodesIndexRoute
  '/leaderboards': typeof LeaderboardsIndexRoute
  '/members': typeof MembersIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/rules': typeof RulesIndexRoute
  '/search': typeof SearchIndexRoute
  '/staff': typeof StaffIndexRoute
  '/store': typeof StoreIndexRoute
  '/terms': typeof TermsIndexRoute
  '/forum/topic/$slug': typeof ForumTopicSlugRoute
  '/forum/view/$slug': typeof ForumViewSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gamemodes/$mode': typeof GamemodesModeRoute
  '/members/$username': typeof MembersUsernameRoute
  '/post/$slug': typeof PostSlugRoute
  '/bearcoin/': typeof BearcoinIndexRoute
  '/bearprime/': typeof BearprimeIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/gamemodes/': typeof GamemodesIndexRoute
  '/leaderboards/': typeof LeaderboardsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/rules/': typeof RulesIndexRoute
  '/search/': typeof SearchIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/store/': typeof StoreIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/forum/topic/$slug': typeof ForumTopicSlugRoute
  '/forum/view/$slug': typeof ForumViewSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/news'
    | '/sitemap.xml'
    | '/gamemodes/$mode'
    | '/members/$username'
    | '/post/$slug'
    | '/bearcoin/'
    | '/bearprime/'
    | '/forum/'
    | '/gamemodes/'
    | '/leaderboards/'
    | '/members/'
    | '/privacy/'
    | '/rules/'
    | '/search/'
    | '/staff/'
    | '/store/'
    | '/terms/'
    | '/forum/topic/$slug'
    | '/forum/view/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/news'
    | '/sitemap.xml'
    | '/gamemodes/$mode'
    | '/members/$username'
    | '/post/$slug'
    | '/bearcoin'
    | '/bearprime'
    | '/forum'
    | '/gamemodes'
    | '/leaderboards'
    | '/members'
    | '/privacy'
    | '/rules'
    | '/search'
    | '/staff'
    | '/store'
    | '/terms'
    | '/forum/topic/$slug'
    | '/forum/view/$slug'
  id:
    | '__root__'
    | '/'
    | '/news'
    | '/sitemap.xml'
    | '/gamemodes/$mode'
    | '/members/$username'
    | '/post/$slug'
    | '/bearcoin/'
    | '/bearprime/'
    | '/forum/'
    | '/gamemodes/'
    | '/leaderboards/'
    | '/members/'
    | '/privacy/'
    | '/rules/'
    | '/search/'
    | '/staff/'
    | '/store/'
    | '/terms/'
    | '/forum/topic/$slug'
    | '/forum/view/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewsRoute: typeof NewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GamemodesModeRoute: typeof GamemodesModeRoute
  MembersUsernameRoute: typeof MembersUsernameRoute
  PostSlugRoute: typeof PostSlugRoute
  BearcoinIndexRoute: typeof BearcoinIndexRoute
  BearprimeIndexRoute: typeof BearprimeIndexRoute
  ForumIndexRoute: typeof ForumIndexRoute
  GamemodesIndexRoute: typeof GamemodesIndexRoute
  LeaderboardsIndexRoute: typeof LeaderboardsIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  RulesIndexRoute: typeof RulesIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StoreIndexRoute: typeof StoreIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
  ForumTopicSlugRoute: typeof ForumTopicSlugRoute
  ForumViewSlugRoute: typeof ForumViewSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/': {
      id: '/rules/'
      path: '/rules'
      fullPath: '/rules/'
      preLoaderRoute: typeof RulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards/': {
      id: '/leaderboards/'
      path: '/leaderboards'
      fullPath: '/leaderboards/'
      preLoaderRoute: typeof LeaderboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamemodes/': {
      id: '/gamemodes/'
      path: '/gamemodes'
      fullPath: '/gamemodes/'
      preLoaderRoute: typeof GamemodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bearprime/': {
      id: '/bearprime/'
      path: '/bearprime'
      fullPath: '/bearprime/'
      preLoaderRoute: typeof BearprimeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bearcoin/': {
      id: '/bearcoin/'
      path: '/bearcoin'
      fullPath: '/bearcoin/'
      preLoaderRoute: typeof BearcoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$username': {
      id: '/members/$username'
      path: '/members/$username'
      fullPath: '/members/$username'
      preLoaderRoute: typeof MembersUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamemodes/$mode': {
      id: '/gamemodes/$mode'
      path: '/gamemodes/$mode'
      fullPath: '/gamemodes/$mode'
      preLoaderRoute: typeof GamemodesModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/view/$slug': {
      id: '/forum/view/$slug'
      path: '/forum/view/$slug'
      fullPath: '/forum/view/$slug'
      preLoaderRoute: typeof ForumViewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/topic/$slug': {
      id: '/forum/topic/$slug'
      path: '/forum/topic/$slug'
      fullPath: '/forum/topic/$slug'
      preLoaderRoute: typeof ForumTopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewsRoute: NewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GamemodesModeRoute: GamemodesModeRoute,
  MembersUsernameRoute: MembersUsernameRoute,
  PostSlugRoute: PostSlugRoute,
  BearcoinIndexRoute: BearcoinIndexRoute,
  BearprimeIndexRoute: BearprimeIndexRoute,
  ForumIndexRoute: ForumIndexRoute,
  GamemodesIndexRoute: GamemodesIndexRoute,
  LeaderboardsIndexRoute: LeaderboardsIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  RulesIndexRoute: RulesIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  StoreIndexRoute: StoreIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
  ForumTopicSlugRoute: ForumTopicSlugRoute,
  ForumViewSlugRoute: ForumViewSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
